version: '3.4'

services:
  oneshot:
    image: forage2d
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src
      - /mnt/data1:/data
      - /home/$USER/Repos:/Repos
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.2'