name: psychopy
channels:
- conda-forge
dependencies:
- python=3.8
- psychopy
- pyaudio
- pip
- pip:
  - psychtoolbox
  - pygame
  - pyo
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"
  - websocket_client